export const data = [
  {
    id: 4,
    description: null,
    default_branch: "master",
    visibility: "private",
    ssh_url_to_repo: "git@example.com:diaspora/diaspora-client.git",
    http_url_to_repo: "http://example.com/diaspora/diaspora-client.git",
    web_url: "http://example.com/diaspora/diaspora-client",
    readme_url:
      "http://example.com/diaspora/diaspora-client/blob/master/README.md",
    tag_list: ["example", "disapora client"],
    owner: {
      id: 3,
      name: "Diaspora",
      created_at: "2013-09-30T13:46:02Z",
    },
    name: "Diaspora Client",
    name_with_namespace: "Diaspora / Diaspora Client",
    path: "diaspora-client",
    path_with_namespace: "diaspora/diaspora-client",
    issues_enabled: true,
    open_issues_count: 1,
    merge_requests_enabled: true,
    jobs_enabled: true,
    wiki_enabled: true,
    snippets_enabled: false,
    can_create_merge_request_in: true,
    resolve_outdated_diff_discussions: false,
    container_registry_enabled: false,
    created_at: "2013-09-30T13:46:02Z",
    last_activity_at: "2013-09-30T13:46:02Z",
    creator_id: 3,
    namespace: {
      id: 3,
      name: "Diaspora",
      path: "diaspora",
      kind: "group",
      full_path: "diaspora",
    },
    import_status: "none",
    archived: false,
    avatar_url:
      "http://example.com/uploads/project/avatar/4/uploads/avatar.png",
    shared_runners_enabled: true,
    forks_count: 0,
    star_count: 0,
    runners_token: "b8547b1dc37721d05889db52fa2f02",
    ci_default_git_depth: 50,
    ci_forward_deployment_enabled: true,
    public_jobs: true,
    shared_with_groups: [],
    only_allow_merge_if_pipeline_succeeds: false,
    allow_merge_on_skipped_pipeline: false,
    restrict_user_defined_variables: false,
    only_allow_merge_if_all_discussions_are_resolved: false,
    remove_source_branch_after_merge: false,
    request_access_enabled: false,
    merge_method: "merge",
    autoclose_referenced_issues: true,
    suggestion_commit_message: null,
    marked_for_deletion_at: "2020-04-03", // Deprecated and will be removed in API v5 in favor of marked_for_deletion_on
    marked_for_deletion_on: "2020-04-03",
    statistics: {
      commit_count: 37,
      storage_size: 1038090,
      repository_size: 1038090,
      wiki_size: 0,
      lfs_objects_size: 0,
      job_artifacts_size: 0,
      packages_size: 0,
      snippets_size: 0,
    },
    _links: {
      self: "http://example.com/api/v4/projects",
      issues: "http://example.com/api/v4/projects/1/issues",
      merge_requests: "http://example.com/api/v4/projects/1/merge_requests",
      repo_branches: "http://example.com/api/v4/projects/1/repository_branches",
      labels: "http://example.com/api/v4/projects/1/labels",
      events: "http://example.com/api/v4/projects/1/events",
      members: "http://example.com/api/v4/projects/1/members",
    },
  },
  {
    id: 6,
    description: null,
    default_branch: "master",
    visibility: "private",
    ssh_url_to_repo: "git@example.com:brightbox/puppet.git",
    http_url_to_repo: "http://example.com/brightbox/puppet.git",
    web_url: "http://example.com/brightbox/puppet",
    readme_url: "http://example.com/brightbox/puppet/blob/master/README.md",
    tag_list: ["example", "puppet"],
    owner: {
      id: 4,
      name: "Brightbox",
      created_at: "2013-09-30T13:46:02Z",
    },
    name: "Puppet",
    name_with_namespace: "Brightbox / Puppet",
    path: "puppet",
    path_with_namespace: "brightbox/puppet",
    issues_enabled: true,
    open_issues_count: 1,
    merge_requests_enabled: true,
    jobs_enabled: true,
    wiki_enabled: true,
    snippets_enabled: false,
    can_create_merge_request_in: true,
    resolve_outdated_diff_discussions: false,
    container_registry_enabled: false,
    created_at: "2013-09-30T13:46:02Z",
    last_activity_at: "2013-09-30T13:46:02Z",
    creator_id: 3,
    namespace: {
      id: 4,
      name: "Brightbox",
      path: "brightbox",
      kind: "group",
      full_path: "brightbox",
    },
    import_status: "none",
    import_error: null,
    permissions: {
      project_access: {
        access_level: 10,
        notification_level: 3,
      },
      group_access: {
        access_level: 50,
        notification_level: 3,
      },
    },
    archived: false,
    avatar_url: null,
    shared_runners_enabled: true,
    forks_count: 0,
    star_count: 0,
    runners_token: "b8547b1dc37721d05889db52fa2f02",
    ci_default_git_depth: 0,
    ci_forward_deployment_enabled: true,
    public_jobs: true,
    shared_with_groups: [],
    only_allow_merge_if_pipeline_succeeds: false,
    allow_merge_on_skipped_pipeline: false,
    restrict_user_defined_variables: false,
    only_allow_merge_if_all_discussions_are_resolved: false,
    remove_source_branch_after_merge: false,
    request_access_enabled: false,
    merge_method: "merge",
    auto_devops_enabled: true,
    auto_devops_deploy_strategy: "continuous",
    repository_storage: "default",
    approvals_before_merge: 0,
    mirror: false,
    mirror_user_id: 45,
    mirror_trigger_builds: false,
    only_mirror_protected_branches: false,
    mirror_overwrites_diverged_branches: false,
    external_authorization_classification_label: null,
    packages_enabled: true,
    service_desk_enabled: false,
    service_desk_address: null,
    autoclose_referenced_issues: true,
    suggestion_commit_message: null,
    statistics: {
      commit_count: 12,
      storage_size: 2066080,
      repository_size: 2066080,
      wiki_size: 0,
      lfs_objects_size: 0,
      job_artifacts_size: 0,
      packages_size: 0,
      snippets_size: 0,
    },
    _links: {
      self: "http://example.com/api/v4/projects",
      issues: "http://example.com/api/v4/projects/1/issues",
      merge_requests: "http://example.com/api/v4/projects/1/merge_requests",
      repo_branches: "http://example.com/api/v4/projects/1/repository_branches",
      labels: "http://example.com/api/v4/projects/1/labels",
      events: "http://example.com/api/v4/projects/1/events",
      members: "http://example.com/api/v4/projects/1/members",
    },
  },
];
