export const data = [
  {
    id: 4,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac ipsum felis. Suspendisse bibendum erat a nisl laoreet laoreet. Donec sit amet justo eget tellus tincidunt tempus at non velit.",
    default_branch: "master",
    visibility: "private",
    web_url: "http://example.com/diaspora/diaspora-client",
    readme_url:
      "http://example.com/diaspora/diaspora-client/blob/master/README.md",
    tag_list: ["example", "disapora client"],
    owner: {
      id: 3,
      name: "Diaspora",
      created_at: "2013-09-30T13:46:02Z",
    },
    name: "Diaspora Client",
    name_with_namespace: "Diaspora / Diaspora Client",
    path: "diaspora-client",
    path_with_namespace: "diaspora/diaspora-client",
    issues_enabled: true,
    open_issues_count: 1,
    merge_requests_enabled: true,
    jobs_enabled: true,
    wiki_enabled: true,
    snippets_enabled: false,
    can_create_merge_request_in: true,
    resolve_outdated_diff_discussions: false,
    container_registry_enabled: false,
    created_at: "2013-09-30T13:46:02Z",
    last_activity_at: "2013-09-30T13:46:02Z",
    creator_id: 3,
    namespace: {
      id: 3,
      name: "Diaspora",
      path: "diaspora",
      kind: "group",
      full_path: "diaspora",
    },
    import_status: "none",
    archived: false,
    avatar_url:
      "http://example.com/uploads/project/avatar/4/uploads/avatar.png",
    shared_runners_enabled: true,
    forks_count: 0,
    star_count: 0,
  },
  {
    id: 6,
    description: null,
    default_branch: "master",
    visibility: "private",
    ssh_url_to_repo: "git@example.com:brightbox/puppet.git",
    http_url_to_repo: "http://example.com/brightbox/puppet.git",
    web_url: "http://example.com/brightbox/puppet",
    readme_url: "http://example.com/brightbox/puppet/blob/master/README.md",
    creator_id: 3,
    namespace: {
      id: 4,
      name: "Brightbox",
      path: "brightbox",
      kind: "group",
      full_path: "brightbox",
    },
    avatar_url: null,
    name: "The best project",
    forks_count: 0,
    star_count: 0,
    statistics: {
      commit_count: 12,
      storage_size: 2066080,
      repository_size: 2066080,
      wiki_size: 0,
      lfs_objects_size: 0,
      job_artifacts_size: 0,
      packages_size: 0,
      snippets_size: 0,
    },
  },
];
